apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kcm.fullname" . }}-manager-role
  labels:
  {{- include "kcm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - operator.cluster.x-k8s.io
  resources:
  - coreproviders
  - infrastructureproviders
  - bootstrapproviders
  - controlplaneproviders
  - ipamproviders
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clusterdeployments
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clusterdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clusterdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - managements
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - accessmanagements
  - clustertemplatechains
  - servicetemplatechains
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - releases
  verbs:
  - get
  - list
  - watch
  - update # labels
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - releases/status
  verbs:
  - update
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - managements/finalizers
  verbs:
  - update
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - managements/status
  - accessmanagements/status
  - clustertemplatechains/status
  - servicetemplatechains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clustertemplates
  - servicetemplates
  - providertemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clustertemplates/finalizers
  - servicetemplates/finalizers
  - providertemplates/finalizers
  verbs:
  - update
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clustertemplates/status
  - servicetemplates/status
  - providertemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - helmcharts
  - helmrepositories
  - gitrepositories
  - buckets
  - ocirepositories
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - create
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - awsclusters
  - awsmanagedclusters
  - azureclusters
  - azureasomanagedclusters
  - dockerclusters
  - openstackclusters
  - vsphereclusters
  - vspheremachines
  - remoteclusters
  - gcpclusters
  - gcpmanagedclusters
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs: {{ include "rbac.viewerVerbs" . | nindent 4 }}
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - credentials
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - credentials/finalizers
  verbs:
  - update
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - credentials/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - providerinterfaces
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - providerinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - providerinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - awsclusterstaticidentities
  - awsclustercontrolleridentities
  - awsclusterroleidentities
  - azureclusteridentities
  - vsphereclusteridentities
  verbs: {{ include "rbac.viewerVerbs" . | nindent 2 }}
- apiGroups:
  - lib.projectsveltos.io
  resources:
  - sveltosclusters
  - sveltosclusters/status
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - config.projectsveltos.io
  resources:
  - profiles
  - clusterprofiles
  - clustersummaries
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - multiclusterservices
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - multiclusterservices/finalizers
  verbs:
  - update
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - multiclusterservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
  - create # copy secrets between namespaces
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs: {{ include "rbac.editorVerbs" . | nindent 2 }}
# managementbackups-ctrl
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - managementbackups
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - managementbackups/finalizers
  verbs:
  - update
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - managementbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - velero.io
  resources:
  - '*'
  verbs:
  - '*'
# managementbackups-ctrl
- apiGroups: # required for autobackup on upgrade
  - apps
  resources:
  - deployments
  verbs:
  - list
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clusteripamclaims
  - clusteripams
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - k0rdent.mirantis.com
  resources:
  - clusteripamclaims/status
  - clusteripams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - ipaddressclaims
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - inclusterippools
  verbs: {{ include "rbac.editorVerbs" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kcm.fullname" . }}-manager-secrets-reader-role
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "kcm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
