controlPlaneNumber: 3
workersNumber: 2

clusterNetwork:
  pods:
    cidrBlocks:
    - "10.244.0.0/16"
  services:
    cidrBlocks:
    - "10.96.0.0/12"
  serviceDomain: "cluster.local"

clusterLabels: {}
clusterAnnotations: {}

ccmRegional: true

identityRef:
  name: ""
  cloudName: ""
  region: ""

bastion:
  enabled: false
  spec:
    sshKeyName: ""
    providerID: ""
    flavor: ""
    image:
      filter:
        name: ""

managedSecurityGroups:
  allowAllInClusterTraffic: false

managedSubnets:
- cidr: 10.6.0.0/24

apiServerLoadBalancer:
  enabled: true

externalNetwork:
  filter:
    name: ""

controlPlane:
  sshKeyName: ""
  providerID: ""
  flavor: ""
  image:
    filter:
      name: ""
  portOpts: []
  rootVolume: {}
  additionalBlockDevices: []
  securityGroups:
    - filter:
        name: "default"
        description: ""
        projectID: ""

worker:
  sshKeyName: ""
  providerID: ""
  flavor: ""
  image:
    filter:
      name: ""
  portOpts: []
  rootVolume: {}
  additionalBlockDevices: []
  securityGroups:
    - filter:
        name: "default"
        description: ""
        projectID: ""

k0s:
  version: v1.32.5+k0s.1
  api:
    extraArgs: {}

